# Generated by Django 2.2.5 on 2019-09-08 03:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self', models.CharField(max_length=100)),
                ('presentation', models.CharField(max_length=100)),
                ('content_sequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('self', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('text', models.TextField()),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Links')),
                ('tag_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.TagType')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrument_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('asset_class', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('primary', models.BooleanField(default=True)),
                ('seo_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('syndicate', models.BooleanField(default=True)),
                ('valid', models.BooleanField(default=True)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('fool_uid', models.IntegerField()),
                ('primary', models.BooleanField(default=True)),
                ('twitter_username', models.CharField(max_length=100)),
                ('small_avatar_url', models.CharField(max_length=100)),
                ('long_bio', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('byline', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributor_type', models.CharField(max_length=100)),
                ('large_avatar_url', models.CharField(max_length=200)),
                ('short_bio', models.TextField()),
                ('author_id', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('disclosure', models.TextField()),
                ('promo', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('visibility', models.IntegerField(default=0)),
                ('article_type', models.CharField(max_length=100)),
                ('publish_at', models.DateTimeField()),
                ('path', models.CharField(max_length=100)),
                ('static_page', models.BooleanField(default=False)),
                ('author_override', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('headline', models.CharField(max_length=100)),
                ('modified', models.DateTimeField()),
                ('product_id', models.IntegerField(default=0)),
                ('video', models.CharField(max_length=100)),
                ('byline', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='articles.Authors')),
                ('bureau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Bureau')),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Collection')),
                ('insturments', models.ManyToManyField(to='articles.Instruments')),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleLinks')),
                ('pitch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Pitch')),
                ('tags', models.ManyToManyField(to='articles.Tags')),
            ],
        ),
    ]
