# Generated by Django 2.2.5 on 2019-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelinks',
            name='content_sequence',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlelinks',
            name='presentation',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlelinks',
            name='self',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='links',
            name='content',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='self',
            field=models.URLField(),
        ),
    ]
