# Generated by Django 2.2.5 on 2019-09-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190910_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='ask_amount',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='bid_amount',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='dailyrange_maximumamount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='gross_margin',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='percent_change',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='percentofsharestraded',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
