# Generated by Django 2.2.5 on 2019-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190910_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='percent_change',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
    ]
