# Generated by Django 2.2.5 on 2019-09-08 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190908_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('url', models.URLField(max_length=100)),
                ('image', models.URLField(max_length=100)),
                ('modified', models.DateTimeField()),
                ('featured', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.Image'),
        ),
    ]
