# Generated by Django 2.2.5 on 2019-09-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190910_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='marketcapamount',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='percentofsharestraded',
            field=models.DecimalField(decimal_places=40, max_digits=45),
        ),
    ]
