# Generated by Django 2.2.5 on 2019-09-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190910_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(null=True, to='articles.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='bureau',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Bureau'),
        ),
        migrations.AlterField(
            model_name='article',
            name='collection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Collection'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(null=True, to='articles.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='insturments',
            field=models.ManyToManyField(null=True, to='articles.Instrument'),
        ),
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleLink'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pitch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Pitch'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, to='articles.Tag'),
        ),
    ]
