# Generated by Django 2.2.5 on 2019-09-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190910_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='articles.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='insturments',
            field=models.ManyToManyField(to='articles.Instrument'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag'),
        ),
    ]
