# Generated by Django 2.2.5 on 2019-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190910_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='collection',
        ),
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ManyToManyField(to='articles.Collection'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='pitch',
        ),
        migrations.AddField(
            model_name='article',
            name='pitch',
            field=models.ManyToManyField(to='articles.Pitch'),
        ),
    ]
