# Generated by Django 2.2.5 on 2019-09-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190910_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bureau',
        ),
        migrations.AddField(
            model_name='article',
            name='bureau',
            field=models.ManyToManyField(to='articles.Bureau'),
        ),
    ]
